### ISSUE TITLE
Create daily, monthly, yearly, climatological plots of Summit data 

### ISSUE THREAD

**Issue by czender** [jaws/jaws#10]
Create four nice plots of the summit data. Thumbnail them and add them to the homepage. The daily plot just shows one day of raw data. The monthly plot shows the full diurnal cycle of all thirty days, along with the daily mean, daily max, and daily min temperatures. The yearly plot shows monthly means with standard deviation of the daily-mean data within each month plotted as an envelope. The climatological seasonal cycle plot shows same, except standard deviations created for each month.

**Comment by ajcse1** [comment]
What does 'summit' mean here? Does it mean the raw data that we have or is it any other dataset?

**Comment by czender** [comment]
It means the GCNet station at Summit.

**Comment by ajcse1** [comment]
#15 Done
