### ISSUE TITLE
Keep tabulation of cumulative stations and station-years

### ISSUE THREAD

**Issue by czender** [jaws/jaws#101]
Please somewhere (on the homepage) add 3 "counters" that display:
1. Number and names of distinct networks handled, e.g., "4 networks: AAWS, GCNet, IMAU, PROMICE"
2. Total number of stations handled (sum of number of stations per handled network)
3. Total number of station-years of data handled (sum of number of years per station)
I would like to include this information in the ESTF talk, so please email me the preliminary numbers, then, at your convenience, add it to the homepage.

**Comment by ajcse1** [comment]
Added section 'Statistics' on homepage
