### ISSUE TITLE
Add SCAR AWS data from BAS

### ISSUE THREAD

**Issue by czender** [jaws/jaws#117]
Please add the SCAR dataset from BAS as the fifth JAWS-ingestible network type.
The SCAR dataset is an amalgam of many stations we already have, and some we do not.
SCAR does not, AFAICT, archive radiation.
It does include pressure, temperature, qwind speed, and wind direction at at least 3-hourly resolution.
Obtainable via anonymous FTP to ftp.bas.ac.uk
Download all *aws.dat files from src/SCAR_EGOMA/AWS
With the ncftp client, this looks like
```
ncftp ftp.bas.ac.uk
cd /src/SCAR_EGOMA/AWS
binary
mget *aws.att
```
My contact is Steve Colwell, email: src at bas.ac.uk

**Comment by ajcse1** [comment]
The header for these files looks like this:
`
AGO_A81
Operated by US
latitude -81.50 longitude 3.74 height 2410m
Data format is: Year, Month, Day, Hour (UTC), Minute, Pressure (hPa), Temperature (Deg C), Wind Speed (knots), Wind Direction (Degrees)
Null values are displayed as -999
Data supplied by the University of Wisconsin
`
I have included 'Operated by' and 'Data supplied by' as following global attributes:
`
operated_by: US
institution: University of Wisconsin
`
Is that fine?
Just for reference, all other networks have 'institution' attribute but none has 'operated_by'

**Comment by czender** [comment]
Yes, that is fine for now.

**Comment by ajcse1** [comment]
Added in version 0.5

**Comment by ajcse1** [comment]
> Obtainable via anonymous FTP to ftp.bas.ac.uk
> Download all *aws.dat files from src/SCAR_EGOMA/AWS
> With the ncftp client, this looks like
> 
> ```
> ncftp ftp.bas.ac.uk
> cd /src/SCAR_EGOMA/AWS
> binary
> mget *aws.att
> ```

@czender Should we include this info to get data for SCAR stations in our documentation? Or is it only for specific users?

**Comment by czender** [comment]
Yes, please include this in the docs. It is for all users.

**Comment by ajcse1** [comment]
Alright
