### ISSUE TITLE
Add PROMICE Metadata

### ISSUE THREAD

**Issue by ajcse1** [jaws/jaws#120]
1. air temperature:  ~2.7 m if no snow layer is present
2. wind: ~3.1 if no snow layer is present
3. radiation: ~2.8m of no snow layer is present

**Comment by ajcse1** [comment]
Add attribute 'sensor_height' to individual variables

**Comment by ajcse1** [comment]
@wenshanw 

> radiation: ~2.8m if no snow layer is present

Is this same for both SW and LW

**Comment by wenshanw** [comment]
Yes, that is correct!

Best,
Wenshan
------------------------------------------------------------------------------
Post-doctoral Scholar
Zender Research Group
Department of Earth System Science
University of California, Irvine
https://sites.google.com/a/uci.edu/wenshanwang/

**Comment by ajcse1** [comment]
Done in v0.5.3
