### ISSUE TITLE
Convert analysis/plot scripts from R to Python and use matplotlib not ggplot

### ISSUE THREAD

**Issue by czender** [jaws/jaws#16]
JAWS was designed, proposed, and funded to be based on Python not R. Please convert the plots for #15 from ggplot/R to matplotlib/Python. I left our discussion about this yesterday thinking that you said you were using Python and importing ggplot. It appears you are using straight R, which is inconsistent with the project design and the desired uniformity/simplicity of the required software stack.

**Comment by ajcse1** [comment]
After our discussion, didn't work more in R, I understood that I have to switch to matplotlib/Python.
I just uploaded these scripts for reference until I uploaded the python scripts. I will remove them.
