### ISSUE TITLE
Analysis plots error

### ISSUE THREAD

**Issue by ajcse1** [jaws/jaws#166]
`
$ jaws --anl=monthly --var=temperature_cs500_1 --anl_yr=2012 --anl_mth=8
GCNet_Summit_20120817.nc
fails with “ERROR: Provide data for each day of the month”
`

**Comment by ajcse1** [comment]
The sample file that we have provided contains data for only 1 day. To run 'monthly' and 'annual' analysis, user needs to have data for a month and year respectively.
Since these data are owned by different network managers, we don't have permission to distribute data for more than a day.

**Comment by czender** [comment]
Recall that we now distribute a single month of data for networks that can use RIGB (right? so that users can try RIGB on the demo data). Please change the analysis demos to use the same monthly datasets as input.

**Comment by ajcse1** [comment]
For RIGB, we need a clear-sky day. So, we are still distributing a single day data but that day is now clear-sky.

**Comment by czender** [comment]
OK. Then just warn on the homepage which examples will only work with more data than the default.

**Comment by ajcse1** [comment]
Yes, updated the instructions
