### ISSUE TITLE
Citing JAWS

### ISSUE THREAD

**Issue by ajcse1** [jaws/jaws#177]
How should users cite JAWS?

Here's an example https://salib.readthedocs.io/en/latest/citations.html

**Comment by czender** [comment]
Please use this for now:
Zender, C. S., W. Wang W., and A. J. Saini, JAWS 1.0: An Extensible
Toolkit to Harmonize and Analyze Polar Automatic Weather Station
Datasets, Manuscript in Preparation for Geosci. Model Dev..

**Comment by ajcse1** [comment]
Added section in documentation
