### ISSUE TITLE
Avoid UPPERCASE variable/attribute/dimension/group names

### ISSUE THREAD

**Issue by czender** [jaws/jaws#19]
Convert TITLE, SOURCE, INSITUTION and REFERNCE to lowercase. URL is fine because it is an acronym. Conventions must have first letter capitalized (that is the CF convention). In general, avoid capital letters for object names unless necessary.
  :TITLE = "Surface Radiation Data from Greenland Climate Network" ;
    :SOURCE = "Surface Observations" ;
    :INSTITUTION = "Cooperative Institute for Research in Enviornmental Sciences" ;
    :REFERENCE = "http://cires.colorado.edu/science/groups/steffen/gcnet/" ;
    :URL = "http://cires.colorado.edu/science/groups/steffen/gcnet/" ;
    :Conventions = "CF-1.6" ;

**Comment by ajcse1** [comment]
Sure, edited for the current files and will keep in mind for future.
