### ISSUE TITLE
Add sample one-day dataset of GCNet raw data

### ISSUE THREAD

**Issue by czender** [jaws/jaws#2]
The sample data should be for one day, the first day of the month so it has the column headers. Truncate it by hand. Upload. Put them all in the sample data directory with names like "gcnet_20160301.txt", "promice_20160301.txt".

**Comment by czender** [comment]
Please "close and comment" this issue by including a link to the dataset that you added to close this issue. Issues should be self-documenting.

**Comment by ajcse1** [comment]
Dataset added and can be found in the sample_data directory as 'gcnet_20130101.txt'
