### ISSUE TITLE
Use correct standard_name and long_name

### ISSUE THREAD

**Issue by czender** [jaws/jaws#21]
You seem to have confused long_name and standard_name. The value of long_name in every variable I checked was in fact its standard_name. Please correct that. long_name is a netCDF (not CF) convention. It should contain the English language text string most appropriate for printing as an axis label when plotting the quantity in question, e.g., 
```
max_air_temperature_1:standard_name = "air_temperature"
max_air_temperature_1:long_name = "Air Temperature"
```
Every variable can have a long_name, which is just what a scientist would call it, with capitalization and whitespace. standard_name requires an entry in the CF standard_name list. Please fix this in all datasets.

**Comment by ajcse1** [comment]
Changed in all datasets.
