### ISSUE TITLE
Use canonical units

### ISSUE THREAD

**Issue by czender** [jaws/jaws#25]
units attribute values should be spelled out in lowercase singular SI units with whitespace separating words and exponents indicated as positive integers > 1 (but no plus sign) or negative integers.  
 ```
windspeed_10m:units = "m/s" ; # Wrong
windspeed_10m:units = "meters second-1" ; # Wrong
windspeed_10m:units = "meter second-1" ; # Right
density:units = "m3/kg" ; # Wrong
density:units = "meter3 kilogram-1" ; # Right
```

**Comment by ajcse1** [comment]
Changed for all datasets
