### ISSUE TITLE
Add CF bounds variable to time coordinate

### ISSUE THREAD

**Issue by czender** [jaws/jaws#29]
The CF document describes what a "bounds" variable is. For JAWS we will name it "time_bounds". So in all datasets "time" needs an attributed named "bounds" with value "time_bounds". Create the variable time_bounds(time,nbnd) to indicate the exact temporal bounds of each value of "time".  The nbnd ("number of bounds") dimension has size 2.

**Comment by ajcse1** [comment]
Created for all datasets.
