### ISSUE TITLE
Add cell_methods attribute

### ISSUE THREAD

**Issue by czender** [jaws/jaws#30]
Please add "cell_methods" attribute to most if not all geophysical variables that have a "time" dimension:

http://cfconventions.org/cf-conventions/cf-conventions.html#cell-methods

Do not add to time_bounds, that is the only exception I know of. So most variables will then look like this:
 ```
 float air_temperature(time) ;
      air_temperature:units = "kelvin" ;
      air_temperature:long_name = "Air Temperature" ;
      air_temperature:standard_name = "air_temperature" ;
      air_temperature:cell_methods = "time: mean" ;
```

**Comment by czender** [comment]
If we ever get _instantaneous_ rather than time-mean AWS data, then its `cell_methods` should be `time: point`.

**Comment by ajcse1** [comment]
Added the attribute for all datasets
