### ISSUE TITLE
Eliminate naked constants

### ISSUE THREAD

**Issue by czender** [jaws/jaws#43]
Naked constants are numbers used on the RHS that should be replaced by symbols. Examples:
		`relative_humidity_1[j] = columns[10]
`
Here 10 is a naked constant because 10 is the ordinal position of the GCNet column that contains relative_humidity_1. Please reimplement as
```
# Define the column locations in one block at the top
idx_relative_humidity_1=10
...
# Use the definitions to populate the data structures
relative_humidity_1[j]=columns[idx_relative_humidity_1]
```
Another example:

`			temperature_cs500_2[j] = float(columns[9]) + 273.15
`
273.15 should be a symbol, not a naked constant, e.g., 

`			temperature_cs500_2[j] = float(columns[9]) + temperature_freezing
`

**Comment by ajcse1** [comment]
Eliminated from all datasets
