### ISSUE TITLE
Use string to numeric conversion functions

### ISSUE THREAD

**Issue by czender** [jaws/jaws#44]
Code that uses strings to check for numerical comparisons is silly and slow. For example:
`		if columns[9] in {'999.0','999.00','999.000','999.0000'}:
`
Figure out a way to safely convert `columns[9]` to a float and use arithmetic comparisons. Ask on StackOverflow if you're not sure

**Comment by ajcse1** [comment]
Now, using numeric comparisons instead of string for all the datasets
