### ISSUE TITLE
Use hashes or array indexes

### ISSUE THREAD

**Issue by czender** [jaws/jaws#46]
This is poor practice. station_number[0] is an index, use it as such, or create a hash table. Ask on StackOverflow if you don't understand that:
```
	if station_number[0] == 1:
		temp_stn = 'gcnet_swiss'
	elif station_number[0] == 2:
		temp_stn = 'gcnet_crawford'
	elif station_number[0] == 3:
		temp_stn = 'gcnet_nasa-u'
	elif station_number[0] == 4:

```

**Comment by ajcse1** [comment]
For GCNet and AAWS, code has been optimized

**Comment by ajcse1** [comment]
Done for PROMICE as well
