### ISSUE TITLE
Calculate time and date intelligently

### ISSUE THREAD

**Issue by czender** [jaws/jaws#47]
"calculating time" (Lines 887--959) of gcnet2nc.py, and the hundreds of lines for "calculating day and month" have the appearance, speed, and robustness of amateurish code. Either use an existing Python module to parse times or write something yourself that is at least ten-times more compact. Learn how to ask a well-posed question on StackOverflow, pose it, and send me the link to the question so I can verify that you are attempting to use best practices. Much of the time and date code in all three network modules is repetitive and needs to be functionalized so it appears in only one place. Once that is done it will be clearer why the conversion code is so slow.

**Comment by ajcse1** [comment]
Defined compact functions to calculate time and date
