### ISSUE TITLE
Test Modules

### ISSUE THREAD

**Issue by ajcse1** [jaws/jaws#49]
Implement unit tests for all scripts

**Comment by czender** [comment]
This is an important task. Has it become clear that JAWS may work for you but not others? At a minimum we need automatic verification that a default call each of the networks works. If you make JAWS a conda-installable package, then you can have TravisCI and AppVeyor automatically test it on a build-matrix of machines after each commit, or each tagged commit (as NCO does). I suggest you look to StackOverflow or GitHub help sites on best practices to turn a Python project into a Conda package and invoke automatic testing.

**Comment by czender** [comment]
Please update and close once Travis is guaranteed working with no false positives

**Comment by czender** [comment]
Please add following tests:
One where as many options as possible are perfomed in one invocation
One that tests compression

**Comment by ajcse1** [comment]
Added both of the above mentioned tests and checked for false positives.
