### ISSUE TITLE
Make plot scripts accept generic files and variable names

### ISSUE THREAD

**Issue by czender** [jaws/jaws#57]
May require having standardized time values, e.g., julian day number, and using metadata for axis labels.

**Comment by ajcse1** [comment]
Plotting can now be done for any network. 
Metadata is being used from converted netCDF file for axis labels.
Need to discuss for standardizing variable names.

**Comment by ajcse1** [comment]
For diurnal plot, x-axis represents hour of the day. Should it range from 1-24 or 0-23? @czender

**Comment by czender** [comment]
Great question. 0 (midnight) to 23 (11 PM).

**Comment by ajcse1** [comment]
Done
