### ISSUE TITLE
Make netCDF4 files use strings not character arrays for station_name

### ISSUE THREAD

**Issue by czender** [jaws/jaws#58]
...and any other text-valued variables (not attributes) as well

**Comment by ajcse1** [comment]
For Python3, it uses string for netCDF4 format.

For Python2, tried different methods with no success. Asked question on SO https://stackoverflow.com/questions/48959201/xarray-store-strings-as-string-data-type-instead-of-char-n-dimensional-ch

**Comment by ajcse1** [comment]
Asked on Xarray google group https://groups.google.com/forum/#!topic/xarray/iNY4nJ2xbDI

**Comment by ajcse1** [comment]
Made changes by using {dtype: 'unicode'} in encoding for text-valued variables.
