### ISSUE TITLE
Add compression options

### ISSUE THREAD

**Issue by czender** [jaws/jaws#63]
Same syntax as NCO compression option

**Comment by ajcse1** [comment]
Added option as '-c' / '--compression'

**Comment by czender** [comment]
Please always use NCO names for options when they are equivalent:

`-L, --dfl_lvl, --deflate lvl	Lempel-Ziv deflation/compression (lvl=0..9) for netCDF4 output
`

**Comment by ajcse1** [comment]
Changed option names. Sure, will keep that in mind from next time.
