### ISSUE TITLE
Re-order attributes long_name, standard_name, units order appear consecutively

### ISSUE THREAD

**Issue by czender** [jaws/jaws#66]
Please re-order the attributes. We want the order to be: long_name, standard_name, units. It appears that _FillValue, when present, might have to be first, and that's OK. But we definitely want units to come after long_name and standard_name. NB: Please use a macro in your editor to do this. Don't waste time doing this by hand. If you don't know how to write a macro to do this, ask me to do it.

**Comment by ajcse1** [comment]
Done
