### ISSUE TITLE
Create list of new standard_names needed for CF convention

### ISSUE THREAD

**Issue by czender** [jaws/jaws#7]
When we encounter a field that has no CF standard_name, add it to a master list of variables that might need a standard_name, along with where it is found and its presumed meaning. Later we will sort these out for submission to CF.

**Comment by czender** [comment]
Add link to this document then close the issue. Always state how you addressed and issue before you close it.

**Comment by ajcse1** [comment]
Added the document and can be found in docs directory as 'standard_names_for_CF'
