### ISSUE TITLE
Find dataset like JAWS having CMR Metadata

### ISSUE THREAD

**Issue by ajcse1** [jaws/jaws#70]

**Comment by czender** [comment]
Look [here ](http://dust.ess.uci.edu/tmp/005_newport_pier-2018.nc)

**Comment by czender** [comment]
Not all the global metadata in that file is CMR, though some appears to be. Look for the "low-hanging fruit", the important attributes, and develop a list of what you think we should add to JAWS, and post it here and we will discuss. You can find contacts at ESIP in Tucson who will know more about CMR compliance.

**Comment by ajcse1** [comment]
Important attributes:
1. data_max, valid_max
2. data_min, valid_min
3. axis for some variables
4. instrument
5. axis for lat and lon

**Comment by ajcse1** [comment]
Global attributes:
1. Platform: ShortName, LongName, Type, Characteristics
2. Instrument
3. Science Keywords
