### ISSUE TITLE
YOPP accreditation

### ISSUE THREAD

**Issue by ajcse1** [jaws/jaws#74]

**Comment by ajcse1** [comment]
Created account and drafted project endorsement.

**Comment by ajcse1** [comment]
Added YOPP_questions.txt in docs directory. It contains all the questions that need to be submitted.

**Comment by czender** [comment]
OK, I filled out answers to these questions. Ready to submit?

**Comment by ajcse1** [comment]
Submitted.

**Comment by ajcse1** [comment]
Amended application based on the reviewers' comments

**Comment by czender** [comment]
Now that YOPP endorsement has been received. Please add NASA and YOPP logos to the JAWS homepage next to the Shark image before my talk tomorrow afternoon :) You can copy the NASA logo from the NCO homepage or get it elsewhere. Then this issue can be closed.

**Comment by ajcse1** [comment]
Done
