### ISSUE TITLE
Add GPS-derived ice velocity

### ISSUE THREAD

**Issue by czender** [jaws/jaws#9]
For stations that archive GPS position, diagnose the ice velocity.

**Comment by ajcse1** [comment]
Calculated for PROMICE using Haversine formula. The new variable is named as ice_velocity_GPS

What standard name should we give to this variable? I looked in the CF table and found the following variables:
land_ice_surface_x_velocity
land_ice_x_velocity
land_ice_basal_x_velocity

**Comment by czender** [comment]
Do you have total velocity or x and y components? It is fine to store all three (x,y,total).
And use land_ice_surface_x_velocity and land_ice_surface_y_velocity.

**Comment by czender** [comment]
Please repeat twice, and add x and y velocities. Positive x is towards east, positive y is towards north. Consider adding "positive" CF attribute to the velocity variables.

**Comment by ajcse1** [comment]
Added both x and y components.
