### ISSUE TITLE
Add new attribute 'original_name'

### ISSUE THREAD

**Issue by ajcse1** [jaws/jaws#90]
Until we don't know the long name of variable, both 'original_name' and 'long_name' should be same

**Comment by ajcse1** [comment]
Currently, the order of attributes is:
    "long_name": "Air Temperature",
    "standard_name": "air_temperature",
    "units": "kelvin",
    "cell_methods": "time: mean",
    "coordinates": "longitude latitude"

Should the 'original_name' come after 'standard_name'?

**Comment by ajcse1** [comment]
Added for all networks

**Comment by czender** [comment]
I do not see and original_name attribute in the sample GCNet dataset produced by
`jaws ~/GCNet_Summit_20140601.txt ~/GCNet_Summit_20140601.nc`
Please verify it works for all networks.

**Comment by ajcse1** [comment]
New version wasn't released after this. Now included in version 0.4.
