### ISSUE TITLE
Update slides for annual review in ~August

### ISSUE THREAD

**Issue by czender** [jaws/jaws#99]
I shared with you both the first annual review template. The review will be at UCI in ~August. NASA personnel will be on-site. The template looks almost identical to the interim review from April. Ajay, please start preparing for the annual review by looking for differences between the interim and annual templates. Where they are the same, simply copy our April slide(s) into the August slide deck. Highlight any new slides needed for the annual review. I will update content once it appears in the the August slide deck. Wenshan, presumably you will want to update some of the science slides. Ajay, we should ask for updated financial data two-three weeks before the review (TBD).

**Comment by wenshanw** [comment]
Got it!
I am thinking something on the clear-sky detection.
If Matt has some results by then, we can probably show that too~

Best,
Wenshan
------------------------------------------------------------------------------
Post-doctoral Scholar
Zender Research Group
Department of Earth System Science
University of California, Irvine
https://sites.google.com/a/uci.edu/wenshanwang/
